# Generated by Django 3.1.3 on 2021-07-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0002_category_color_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.CharField(max_length=250)),
                ('retrieval_date', models.CharField(default='2021/07/08 02:31:26', max_length=250)),
                ('linkedin_user', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
