# Generated by Django 3.1.3 on 2021-07-07 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0003_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
