# Generated by Django 3.1.3 on 2021-07-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0005_auto_20210708_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.DateTimeField(default='2021/07/08 03:34:48'),
        ),
    ]
