# Generated by Django 3.1.3 on 2021-07-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0006_auto_20210708_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.CharField(default='2021-07-08 03:52:43', max_length=250),
        ),
    ]
