# Generated by Django 3.1.3 on 2021-07-07 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0007_auto_20210708_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 4, 29, 55, 700936)),
        ),
    ]
