# Generated by Django 3.1.3 on 2021-07-08 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0009_auto_20210708_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='areapin',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 22, 58, 40, 233696)),
        ),
    ]
