# Generated by Django 3.1.3 on 2021-07-08 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0010_auto_20210708_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 1, 56, 1, 324799)),
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housename', models.CharField(max_length=250)),
                ('housecolor', models.ManyToManyField(to='newapp2.Color')),
            ],
        ),
    ]
