# Generated by Django 3.1.3 on 2021-07-12 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp2', '0012_auto_20210712_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amt', models.FloatField()),
                ('paid_status', models.BooleanField(default=False)),
                ('order_dt', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('process', 'In Process'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='process', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='retrieval_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 1, 30, 10, 238090)),
        ),
    ]
